# Analyse exploratoire des données (langage R)

In [1]:
# Chargement des librairies nécessaires
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(GGally)
library(plotly)
library(corrplot)
library(reshape2)
library(FactoMineR) 
library(factoextra)
library(glmnet) 
library(ggfortify)
library(pROC)
library(ROCR)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ lubridate 1.9.5     ✔ tibble    3.3.1
✔ purrr     1.2.1     ✔ tidyr     1.3.2
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : 'gridExtra'


L'objet suivant est masqué depuis 'package:dplyr':

    combine



Attachement du package : 'plotly'


L'objet suivant est masqué depuis 'package:ggplot2':

    last_plot


L'objet suivant est masqué depuis 'package:stats':

    filter


L'objet suivant est masqué depuis 'package:graphics':

    layout


corrplot 0.95 loaded


Attachement du package : 'reshape2'


L'objet suivant est masqué depuis 'package:tidyr':

    smiths


Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa

Le chargement a nécessité le package : Matrix


Attachement du package : 'Matrix'


Les objets suivants sont masqués depuis 'package:tidyr':

    expand, pack, unpack


Loaded glmnet 4.1-10

Type 'citation("pROC")' for a citation.


Attachement du package : 'pROC'


Les objets suivants sont masqués depuis 'package:stats':

    cov, smooth, var

In [2]:
data= read.table("C:\\Users\\Utilisateur\\Desktop\\Projet_Machine_Learning\\healthcare_synthetic_data.csv",sep=",",header=TRUE)
#head(data)
#summary(data)

**Transformation des données**

In [3]:
#on enlève patient_ID ( A EXECUTER 1 SEULE FOIS)
data=data[,-1]

In [4]:
#Changement du type des variables qualitatives en facteurs
data[,"Gender"]= as.factor(data[,"Gender"])
data[,"Smoking_Status"]= as.factor(data[,"Smoking_Status"])
data[,"Alcohol_Consumption"]= as.factor(data[,"Alcohol_Consumption"])
data[,"Physical_Activity_Level"]= as.factor(data[,"Physical_Activity_Level"])
data[,"Family_History"]= as.factor(data[,"Family_History"])
data[,"Stress_Level"]= as.factor(data[,"Stress_Level"])
data[,"Heart_Disease_Risk"]= as.factor(data[,"Heart_Disease_Risk"])
data[,"Sleep_Hours"]= as.factor(data[,"Sleep_Hours"])

In [5]:
#Tranformation (racine carrée) de Weight_kg et BMI pour centrer les densitées
options(repr.plot.width = 10, repr.plot.height = 5)
data[,"SBMI"]=sqrt(data[,"BMI"])
data[,"SWeight"]=sqrt(data[,"Weight_kg"])
#sg4=ggplot(data,aes(x=SBMI)) + geom_density(linewidth=1,col="darkolivegreen") + geom_histogram(alpha=0.6,aes(y=after_stat(density)))
#sg3=ggplot(data,aes(x=SWeight)) + geom_density(linewidth=1,col="darkolivegreen") + geom_histogram(alpha=0.6,aes(y=after_stat(density)))
#grid.arrange(g3,g4,sg3,sg4,ncol=2)

# Prediction de la variable Heart_Disease_Risk

## 1.Division du jeu de données en un échantillon d’apprentissage et un échantillon test

Pourquoi cette étape est-elle nécessaire lorsque nous nous concentrons sur les performances des algorithmes ?

In [6]:
library(caret)

Le chargement a nécessité le package : lattice


Attachement du package : 'caret'


L'objet suivant est masqué depuis 'package:purrr':

    lift

In [7]:
#on enlève les colonnes weight et BMI que l'on a transformé
data_clean=data[,-c(4,5)]
head(data_clean)

  Age Gender Height_cm Systolic_BP Diastolic_BP Cholesterol_Total
1 60  0      146.9     140          89          217
2 53  0      161.8     128          81          203
3 62  1      174.7     141         100          173
4 73  1      173.3     136          96          193
5 52  1      178.6     122          80          236
6 52  0      159.6     134          92          225
  Cholesterol_LDL Cholesterol_HDL Fasting_Blood_Sugar Smoking_Status
1 151             52               83                 0
2 119             38              116                 0
3 124             45               90                 0
4 117             45               81                 0
5 153             41               79                 0
6 155             48              103                 0
  Alcohol_Consumption Physical_Activity_Level Family_History Stress_Level
1 1                   3                       0              1
2 0                   1                       0              7
3 0                   0                       0              1
4 0                   1                       0              2
5 1                   2                       0              2
6 0                   1                       1              4
  Sleep_Hours Heart_Disease_Risk SBMI     SWeight
1 8           0                  4.878524 7.162402
2 9           0                  5.412947 8.752143
3 7           1                  5.504544 9.612492
4 7           1                  4.785394 8.300602
5 6           0                  5.000000 8.933085
6 8           0                  4.868265 7.765307

In [8]:
set.seed(131)
trainIndex = createDataPartition(data_clean$Heart_Disease_Risk,p=0.8,list = FALSE)
dataTrain = data_clean[ trainIndex,]
dataTest = data_clean[-trainIndex,]

## 2. Modèle de régression logistique

Heart_Disease_Risk est une variable binaire, on utilise donc un modèle linéaire généralisé ( régression logistique)

### Modèle sans intéraction entre les variables

In [9]:
# estimation du modèle complet(sans interactions)
reglog = glm(Heart_Disease_Risk ~. , data = dataTrain, family = binomial(link="logit"))
# significativité des paramètres
anova(reglog, test = "Chisq")

                        Df Deviance     Resid. Df Resid. Dev Pr(>Chi)
NULL                    NA           NA 11999     16438.38              NA
Age                      1 3.330504e+02 11998     16105.33    2.081636e-74
Gender                   1 5.432754e-01 11997     16104.79    4.610785e-01
Height_cm                1 6.755591e-01 11996     16104.11    4.111201e-01
Systolic_BP              1 2.270577e+02 11995     15877.06    2.612348e-51
Diastolic_BP             1 2.018179e-01 11994     15876.86    6.532575e-01
Cholesterol_Total        1 5.748988e+01 11993     15819.37    3.397228e-14
Cholesterol_LDL          1 1.919658e+01 11992     15800.17    1.179244e-05
Cholesterol_HDL          1 3.190611e+01 11991     15768.26    1.618070e-08
Fasting_Blood_Sugar      1 1.978876e+02 11990     15570.37    6.036950e-45
Smoking_Status           1 1.631597e+03 11989     13938.78    0.000000e+00
Alcohol_Consumption      2 2.820909e+00 11987     13935.96    2.440323e-01
Physical_Activity_Level  3 3.959289e+02 11984     13540.03    1.686418e-85
Family_History           1 6.046548e+02 11983     12935.37   1.626885e-133
Stress_Level             9 1.976866e+02 11974     12737.69    1.011745e-37
Sleep_Hours              6 2.905584e+01 11968     12708.63    5.937427e-05
SBMI                     1 4.224818e+01 11967     12666.38    8.039498e-11
SWeight                  1 8.065211e-02 11966     12666.30    7.764156e-01

Il est pertinent de se demander si on peut simplifier le modèle en selectionnant seulement les variables significatives. On utilise d'abord le critère AIC (comparaison avec BIC ??)

In [11]:
# Recherche d'un modèle optimal au sens d'Akaïke
reglog.stepAIC = step(reglog, direction = "backward") # éventuellement tester avec direction= "both"

Start:  AIC=12734.3
Heart_Disease_Risk ~ Age + Gender + Height_cm + Systolic_BP +
    Diastolic_BP + Cholesterol_Total + Cholesterol_LDL + Cholesterol_HDL +
    Fasting_Blood_Sugar + Smoking_Status + Alcohol_Consumption +
    Physical_Activity_Level + Family_History + Stress_Level +
    Sleep_Hours + SBMI + SWeight

                          Df Deviance   AIC
- SWeight                  1    12666 12732
- Height_cm                1    12666 12732
- Diastolic_BP             1    12666 12732
- Cholesterol_Total        1    12667 12733
- SBMI                     1    12667 12733
- Gender                   1    12667 12733
- Alcohol_Consumption      2    12669 12733
<none>                          12666 12734
- Cholesterol_HDL          1    12672 12738
- Sleep_Hours              6    12695 12751
- Cholesterol_LDL          1    12693 12759
- Age                      1    12741 12807
- Systolic_BP              1    12744 12810
- Stress_Level             9    12863 12913
- Fasting_Blood_Sugar      1    12872 12938
- Physical_Activity_Level  3    13097 13159
- Family_History           1    13268 13334
- Smoking_Status           1    14523 14589

Step:  AIC=12732.38
Heart_Disease_Risk ~ Age + Gender + Height_cm + Systolic_BP +
    Diastolic_BP + Cholesterol_Total + Cholesterol_LDL + Cholesterol_HDL +
    Fasting_Blood_Sugar + Smoking_Status + Alcohol_Consumption +
    Physical_Activity_Level + Family_History + Stress_Level +
    Sleep_Hours + SBMI

                          Df Deviance   AIC
- Diastolic_BP             1    12667 12731
- Height_cm                1    12667 12731
- Gender                   1    12667 12731
- Cholesterol_Total        1    12667 12731
- Alcohol_Consumption      2    12670 12732
<none>                          12666 12732
- Cholesterol_HDL          1    12672 12736
- Sleep_Hours              6    12695 12749
- Cholesterol_LDL          1    12693 12757
- SBMI                     1    12709 12773
- Age                      1    12742 12806
- Systolic_BP              1    12744 12808
- Stress_Level             9    12863 12911
- Fasting_Blood_Sugar      1    12872 12936
- Physical_Activity_Level  3    13097 13157
- Family_History           1    13269 13333
- Smoking_Status           1    14523 14587

Step:  AIC=12730.61
Heart_Disease_Risk ~ Age + Gender + Height_cm + Systolic_BP +
    Cholesterol_Total + Cholesterol_LDL + Cholesterol_HDL + Fasting_Blood_Sugar +
    Smoking_Status + Alcohol_Consumption + Physical_Activity_Level +
    Family_History + Stress_Level + Sleep_Hours + SBMI

                          Df Deviance   AIC
- Height_cm                1    12667 12729
- Gender                   1    12667 12729
- Cholesterol_Total        1    12667 12729
- Alcohol_Consumption      2    12670 12730
<none>                          12667 12731
- Cholesterol_HDL          1    12672 12734
- Sleep_Hours              6    12695 12747
- Cholesterol_LDL          1    12693 12755
- SBMI                     1    12709 12771
- Age                      1    12742 12804
- Systolic_BP              1    12845 12907
- Stress_Level             9    12863 12909
- Fasting_Blood_Sugar      1    12872 12934
- Physical_Activity_Level  3    13097 13155
- Family_History           1    13269 13331
- Smoking_Status           1    14523 14585

Step:  AIC=12728.88
Heart_Disease_Risk ~ Age + Gender + Systolic_BP + Cholesterol_Total +
    Cholesterol_LDL + Cholesterol_HDL + Fasting_Blood_Sugar +
    Smoking_Status + Alcohol_Consumption + Physical_Activity_Level +
    Family_History + Stress_Level + Sleep_Hours + SBMI

                          Df Deviance   AIC
- Gender                   1    12667 12727
- Cholesterol_Total        1    12667 12727
- Alcohol_Consumption      2    12670 12728
<none>                          12667 12729
- Cholesterol_HDL          1    12672 12732
- Sleep_Hours              6    12696 12746
- Cholesterol_LDL          1    12693 12753
- SBMI                     1    12709 12769
- Age                      1    12742 12802
- Systolic_BP              1    12846 12906
- Stress_Level             9    12864 12908
- Fasting_Blood_Sugar      1    12872 12932
- Physical_Activity_Level  3    13098 13154
- Family_History           1    13270 13330
- Smoking_Status           1    14524 14584

Step:  AIC=12727.12
Heart_Disease_Risk ~ Age + Systolic_BP + Cholesterol_Total +
    Cholesterol_LDL + Cholesterol_HDL + Fasting_Blood_Sugar +
    Smoking_Status + Alcohol_Consumption + Physical_Activity_Level +
    Family_History + Stress_Level + Sleep_Hours + SBMI

                          Df Deviance   AIC
- Cholesterol_Total        1    12668 12726
- Alcohol_Consumption      2    12670 12726
<none>                          12667 12727
- Cholesterol_HDL          1    12673 12731
- Sleep_Hours              6    12696 12744
- Cholesterol_LDL          1    12694 12752
- SBMI                     1    12712 12770
- Age                      1    12742 12800
- Systolic_BP              1    12846 12904
- Stress_Level             9    12864 12906
- Fasting_Blood_Sugar      1    12872 12930
- Physical_Activity_Level  3    13098 13152
- Family_History           1    13270 13328
- Smoking_Status           1    14524 14582

Step:  AIC=12725.62
Heart_Disease_Risk ~ Age + Systolic_BP + Cholesterol_LDL + Cholesterol_HDL +
    Fasting_Blood_Sugar + Smoking_Status + Alcohol_Consumption +
    Physical_Activity_Level + Family_History + Stress_Level +
    Sleep_Hours + SBMI

                          Df Deviance   AIC
- Alcohol_Consumption      2    12671 12725
<none>                          12668 12726
- Cholesterol_HDL          1    12673 12729
- Sleep_Hours              6    12696 12742
- SBMI                     1    12712 12768
- Cholesterol_LDL          1    12725 12781
- Age                      1    12744 12800
- Systolic_BP              1    12847 12903
- Stress_Level             9    12864 12904
- Fasting_Blood_Sugar      1    12873 12929
- Physical_Activity_Level  3    13098 13150
- Family_History           1    13270 13326
- Smoking_Status           1    14525 14581

Step:  AIC=12724.7
Heart_Disease_Risk ~ Age + Systolic_BP + Cholesterol_LDL + Cholesterol_HDL +
    Fasting_Blood_Sugar + Smoking_Status + Physical_Activity_Level +
    Family_History + Stress_Level + Sleep_Hours + SBMI

                          Df Deviance   AIC
<none>                          12671 12725
- Cholesterol_HDL          1    12676 12728
- Sleep_Hours              6    12699 12741
- SBMI                     1    12715 12767
- Cholesterol_LDL          1    12728 12780
- Age                      1    12747 12799
- Systolic_BP              1    12850 12902
- Stress_Level             9    12867 12903
- Fasting_Blood_Sugar      1    12876 12928
- Physical_Activity_Level  3    13102 13150
- Family_History           1    13272 13324
- Smoking_Status           1    14528 14580

In [12]:
anova(reglog.stepAIC,test="Chisq")

                        Df Deviance   Resid. Df Resid. Dev Pr(>Chi)
NULL                    NA         NA 11999     16438.38              NA
Age                      1  333.05045 11998     16105.33    2.081636e-74
Systolic_BP              1  227.16047 11997     15878.17    2.480927e-51
Cholesterol_LDL          1   75.68844 11996     15802.48    3.321459e-18
Cholesterol_HDL          1   30.50806 11995     15771.98    3.324821e-08
Fasting_Blood_Sugar      1  199.17945 11994     15572.80    3.154255e-45
Smoking_Status           1 1631.69029 11993     13941.11    0.000000e+00
Physical_Activity_Level  3  396.37344 11990     13544.73    1.351091e-85
Family_History           1  603.82807 11989     12940.91   2.461315e-133
Stress_Level             9  197.04437 11980     12743.86    1.379204e-37
Sleep_Hours              6   29.02864 11974     12714.83    6.008231e-05
SBMI                     1   44.13373 11973     12670.70    3.066910e-11

In [13]:
#matrice de confusion
table(reglog$fitted.values > 0.5, dataTrain[, "Heart_Disease_Risk"])
table(reglog.stepAIC$fitted.values > 0.5, dataTrain[, "Heart_Disease_Risk"])

           0    1
  FALSE 5494 1851
  TRUE  1274 3381

           0    1
  FALSE 5492 1848
  TRUE  1276 3384

### Modèle avec intéractions

Nous travaillons avec un grand nombre de variables et donc d'interactions ce qui peut donner des warnings et être long si on essaye d'estimer le modèle avec toutes les interactions possibles d'un coup. Nous allons donc utiliser deux méthodes qui permettent d'éviter le problème en selectionnant directement les variables et intéractions siginificatives:

- Une procédure stepwise de selection de variable sur critère AIC
- Une pénalisation L1 (LASSO)

In [14]:
#première méthode
# estimation du modèle avec interactions en partant du modèle constant
reglog.inter = glm(Heart_Disease_Risk ~ 1, data = dataTrain,family = binomial)
# algorithme stepwise en précisant le plus grand 
# modèle possible
reglog.inter.step = step(reglog.inter, direction = "both",
    scope = list(lower = ~1, upper = ~(Age + Gender + Height_cm + SWeight + SBMI + Systolic_BP + Diastolic_BP +Cholesterol_Total + Cholesterol_LDL
                                      + Cholesterol_HDL +  Fasting_Blood_Sugar + Smoking_Status +  Alcohol_Consumption + Physical_Activity_Level + 
                                       Family_History + Stress_Level + Sleep_Hours)^2))

Start:  AIC=16440.38
Heart_Disease_Risk ~ 1

                          Df Deviance   AIC
+ Smoking_Status           1    14896 14900
+ Family_History           1    15986 15990
+ Systolic_BP              1    15995 15999
+ Age                      1    16105 16109
+ Fasting_Blood_Sugar      1    16121 16125
+ Physical_Activity_Level  3    16129 16137
+ Diastolic_BP             1    16158 16162
+ Cholesterol_Total        1    16216 16220
+ Cholesterol_LDL          1    16216 16220
+ SBMI                     1    16246 16250
+ SWeight                  1    16299 16303
+ Stress_Level             9    16292 16312
+ Cholesterol_HDL          1    16386 16390
+ Sleep_Hours              6    16418 16432
<none>                          16438 16440
+ Height_cm                1    16437 16441
+ Gender                   1    16438 16442
+ Alcohol_Consumption      2    16436 16442

Step:  AIC=14900.3
Heart_Disease_Risk ~ Smoking_Status

                          Df Deviance   AIC
+ Family_History           1    14364 14370
+ Systolic_BP              1    14426 14432
+ Age                      1    14508 14514
+ Physical_Activity_Level  3    14532 14542
+ Fasting_Blood_Sugar      1    14539 14545
+ Diastolic_BP             1    14600 14606
+ Cholesterol_Total        1    14642 14648
+ Cholesterol_LDL          1    14648 14654
+ SBMI                     1    14693 14699
+ Stress_Level             9    14716 14738
+ SWeight                  1    14754 14760
+ Cholesterol_HDL          1    14843 14849
+ Sleep_Hours              6    14873 14889
<none>                          14896 14900
+ Height_cm                1    14896 14902
+ Gender                   1    14896 14902
+ Alcohol_Consumption      2    14894 14902
- Smoking_Status           1    16438 16440

Step:  AIC=14369.54
Heart_Disease_Risk ~ Smoking_Status + Family_History

                                Df Deviance   AIC
+ Systolic_BP                    1    13866 13874
+ Age                            1    13943 13951
+ Physical_Activity_Level        3    13983 13995
+ Fasting_Blood_Sugar            1    13997 14005
+ Diastolic_BP                   1    14046 14054
+ Cholesterol_Total              1    14095 14103
+ Cholesterol_LDL                1    14098 14106
+ SBMI                           1    14155 14163
+ Stress_Level                   9    14191 14215
+ SWeight                        1    14217 14225
+ Cholesterol_HDL                1    14310 14318
+ Sleep_Hours                    6    14340 14358
<none>                                14364 14370
+ Alcohol_Consumption            2    14361 14371
+ Height_cm                      1    14363 14371
+ Smoking_Status:Family_History  1    14363 14371
+ Gender                         1    14363 14371
- Family_History                 1    14896 14900
- Smoking_Status                 1    15986 15990

Step:  AIC=13874.29
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP

                                Df Deviance   AIC
+ Physical_Activity_Level        3    13461 13475
+ Fasting_Blood_Sugar            1    13577 13587
+ Cholesterol_LDL                1    13700 13710
+ Stress_Level                   9    13687 13713
+ Age                            1    13704 13714
+ Cholesterol_Total              1    13712 13722
+ SBMI                           1    13757 13767
+ SWeight                        1    13789 13799
+ Cholesterol_HDL                1    13832 13842
+ Sleep_Hours                    6    13840 13860
+ Systolic_BP:Smoking_Status     1    13864 13874
<none>                                13866 13874
+ Alcohol_Consumption            2    13863 13875
+ Height_cm                      1    13866 13876
+ Gender                         1    13866 13876
+ Smoking_Status:Family_History  1    13866 13876
+ Systolic_BP:Family_History     1    13866 13876
+ Diastolic_BP                   1    13866 13876
- Systolic_BP                    1    14364 14370
- Family_History                 1    14426 14432
- Smoking_Status                 1    15522 15528

Step:  AIC=13474.86
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level

                                         Df Deviance   AIC
+ Fasting_Blood_Sugar                     1    13161 13177
+ Stress_Level                            9    13274 13306
+ Cholesterol_LDL                         1    13292 13308
+ Age                                     1    13301 13317
+ Cholesterol_Total                       1    13309 13325
+ SBMI                                    1    13342 13358
+ SWeight                                 1    13378 13394
+ Cholesterol_HDL                         1    13427 13443
+ Sleep_Hours                             6    13433 13459
+ Systolic_BP:Smoking_Status              1    13458 13474
<none>                                         13461 13475
+ Height_cm                               1    13460 13476
+ Physical_Activity_Level:Family_History  3    13456 13476
+ Gender                                  1    13460 13476
+ Diastolic_BP                            1    13461 13477
+ Alcohol_Consumption                     2    13459 13477
+ Smoking_Status:Family_History           1    13461 13477
+ Systolic_BP:Family_History              1    13461 13477
+ Smoking_Status:Physical_Activity_Level  3    13460 13480
+ Systolic_BP:Physical_Activity_Level     3    13461 13481
- Physical_Activity_Level                 3    13866 13874
- Systolic_BP                             1    13983 13995
- Family_History                          1    14040 14052
- Smoking_Status                          1    15181 15193

Step:  AIC=13177.39
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level + Fasting_Blood_Sugar

                                              Df Deviance   AIC
+ Stress_Level                                 9    12971 13005
+ Cholesterol_LDL                              1    13018 13036
+ Cholesterol_Total                            1    13039 13057
+ Age                                          1    13045 13063
+ SBMI                                         1    13094 13112
+ SWeight                                      1    13111 13129
+ Cholesterol_HDL                              1    13135 13153
+ Sleep_Hours                                  6    13133 13161
+ Systolic_BP:Smoking_Status                   1    13158 13176
<none>                                              13161 13177
+ Fasting_Blood_Sugar:Physical_Activity_Level  3    13156 13178
+ Height_cm                                    1    13160 13178
+ Gender                                       1    13161 13179
+ Diastolic_BP                                 1    13161 13179
+ Alcohol_Consumption                          2    13159 13179
+ Smoking_Status:Family_History                1    13161 13179
+ Fasting_Blood_Sugar:Smoking_Status           1    13161 13179
+ Systolic_BP:Fasting_Blood_Sugar              1    13161 13179
+ Fasting_Blood_Sugar:Family_History           1    13161 13179
+ Systolic_BP:Family_History                   1    13161 13179
+ Physical_Activity_Level:Family_History       3    13158 13180
+ Smoking_Status:Physical_Activity_Level       3    13160 13182
+ Systolic_BP:Physical_Activity_Level          3    13161 13183
- Fasting_Blood_Sugar                          1    13461 13475
- Physical_Activity_Level                      3    13577 13587
- Systolic_BP                                  1    13603 13617
- Family_History                               1    13749 13763
- Smoking_Status                               1    14923 14937

Step:  AIC=13004.81
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level + Fasting_Blood_Sugar + Stress_Level

                                              Df Deviance   AIC
+ Cholesterol_LDL                              1    12825 12861
+ Cholesterol_Total                            1    12847 12883
+ Age                                          1    12850 12886
+ SBMI                                         1    12904 12940
+ SWeight                                      1    12923 12959
+ Cholesterol_HDL                              1    12944 12980
+ Sleep_Hours                                  6    12943 12989
+ Systolic_BP:Smoking_Status                   1    12967 13003
<none>                                              12971 13005
+ Fasting_Blood_Sugar:Physical_Activity_Level  3    12966 13006
+ Height_cm                                    1    12970 13006
+ Gender                                       1    12970 13006
+ Alcohol_Consumption                          2    12968 13006
+ Diastolic_BP                                 1    12970 13006
+ Systolic_BP:Family_History                   1    12971 13007
+ Smoking_Status:Family_History                1    12971 13007
+ Systolic_BP:Fasting_Blood_Sugar              1    12971 13007
+ Fasting_Blood_Sugar:Smoking_Status           1    12971 13007
+ Fasting_Blood_Sugar:Family_History           1    12971 13007
+ Physical_Activity_Level:Family_History       3    12967 13007
+ Smoking_Status:Physical_Activity_Level       3    12970 13010
+ Systolic_BP:Physical_Activity_Level          3    12970 13010
+ Family_History:Stress_Level                  9    12962 13014
+ Smoking_Status:Stress_Level                  9    12964 13016
+ Systolic_BP:Stress_Level                     9    12965 13017
+ Fasting_Blood_Sugar:Stress_Level             9    12966 13018
+ Physical_Activity_Level:Stress_Level        27    12942 13030
- Stress_Level                                 9    13161 13177
- Fasting_Blood_Sugar                          1    13274 13306
- Physical_Activity_Level                      3    13394 13422
- Systolic_BP                                  1    13420 13452
- Family_History                               1    13552 13584
- Smoking_Status                               1    14775 14807

Step:  AIC=12860.95
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level + Fasting_Blood_Sugar + Stress_Level +
    Cholesterol_LDL

                                              Df Deviance   AIC
+ Age                                          1    12767 12805
+ SBMI                                         1    12781 12819
+ SWeight                                      1    12793 12831
+ Cholesterol_HDL                              1    12805 12843
+ Sleep_Hours                                  6    12796 12844
+ Cholesterol_LDL:Physical_Activity_Level      3    12814 12856
+ Cholesterol_LDL:Fasting_Blood_Sugar          1    12820 12858
+ Cholesterol_Total                            1    12821 12859
+ Systolic_BP:Smoking_Status                   1    12822 12860
<none>                                              12825 12861
+ Cholesterol_LDL:Family_History               1    12823 12861
+ Fasting_Blood_Sugar:Physical_Activity_Level  3    12819 12861
+ Alcohol_Consumption                          2    12822 12862
+ Cholesterol_LDL:Smoking_Status               1    12824 12862
+ Height_cm                                    1    12824 12862
+ Gender                                       1    12825 12863
+ Diastolic_BP                                 1    12825 12863
+ Systolic_BP:Cholesterol_LDL                  1    12825 12863
+ Systolic_BP:Family_History                   1    12825 12863
+ Systolic_BP:Fasting_Blood_Sugar              1    12825 12863
+ Smoking_Status:Family_History                1    12825 12863
+ Fasting_Blood_Sugar:Family_History           1    12825 12863
+ Fasting_Blood_Sugar:Smoking_Status           1    12825 12863
+ Physical_Activity_Level:Family_History       3    12821 12863
+ Smoking_Status:Physical_Activity_Level       3    12824 12866
+ Systolic_BP:Physical_Activity_Level          3    12824 12866
+ Family_History:Stress_Level                  9    12817 12871
+ Smoking_Status:Stress_Level                  9    12818 12872
+ Systolic_BP:Stress_Level                     9    12818 12872
+ Cholesterol_LDL:Stress_Level                 9    12819 12873
+ Fasting_Blood_Sugar:Stress_Level             9    12820 12874
+ Physical_Activity_Level:Stress_Level        27    12797 12887
- Cholesterol_LDL                              1    12971 13005
- Stress_Level                                 9    13018 13036
- Fasting_Blood_Sugar                          1    13102 13136
- Systolic_BP                                  1    13192 13226
- Physical_Activity_Level                      3    13251 13281
- Family_History                               1    13417 13451
- Smoking_Status                               1    14653 14687

Step:  AIC=12804.77
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level + Fasting_Blood_Sugar + Stress_Level +
    Cholesterol_LDL + Age

                                              Df Deviance   AIC
+ SBMI                                         1    12705 12745
+ SWeight                                      1    12722 12762
+ Cholesterol_HDL                              1    12744 12784
+ Sleep_Hours                                  6    12738 12788
+ Cholesterol_LDL:Physical_Activity_Level      3    12756 12800
+ Cholesterol_LDL:Fasting_Blood_Sugar          1    12762 12802
+ Age:Smoking_Status                           1    12764 12804
+ Systolic_BP:Smoking_Status                   1    12764 12804
<none>                                              12767 12805
+ Age:Fasting_Blood_Sugar                      1    12765 12805
+ Cholesterol_LDL:Family_History               1    12765 12805
+ Fasting_Blood_Sugar:Physical_Activity_Level  3    12761 12805
+ Age:Systolic_BP                              1    12766 12806
+ Alcohol_Consumption                          2    12764 12806
+ Cholesterol_LDL:Smoking_Status               1    12766 12806
+ Age:Family_History                           1    12766 12806
+ Height_cm                                    1    12766 12806
+ Gender                                       1    12766 12806
+ Diastolic_BP                                 1    12767 12807
+ Cholesterol_Total                            1    12767 12807
+ Systolic_BP:Cholesterol_LDL                  1    12767 12807
+ Systolic_BP:Fasting_Blood_Sugar              1    12767 12807
+ Smoking_Status:Family_History                1    12767 12807
+ Age:Cholesterol_LDL                          1    12767 12807
+ Fasting_Blood_Sugar:Smoking_Status           1    12767 12807
+ Systolic_BP:Family_History                   1    12767 12807
+ Fasting_Blood_Sugar:Family_History           1    12767 12807
+ Physical_Activity_Level:Family_History       3    12763 12807
+ Age:Physical_Activity_Level                  3    12766 12810
+ Smoking_Status:Physical_Activity_Level       3    12766 12810
+ Systolic_BP:Physical_Activity_Level          3    12766 12810
+ Family_History:Stress_Level                  9    12759 12815
+ Smoking_Status:Stress_Level                  9    12759 12815
+ Cholesterol_LDL:Stress_Level                 9    12760 12816
+ Systolic_BP:Stress_Level                     9    12760 12816
+ Fasting_Blood_Sugar:Stress_Level             9    12762 12818
+ Age:Stress_Level                             9    12764 12820
+ Physical_Activity_Level:Stress_Level        27    12740 12832
- Age                                          1    12825 12861
- Cholesterol_LDL                              1    12850 12886
- Stress_Level                                 9    12963 12983
- Systolic_BP                                  1    12995 13031
- Fasting_Blood_Sugar                          1    13017 13053
- Physical_Activity_Level                      3    13191 13223
- Family_History                               1    13366 13402
- Smoking_Status                               1    14612 14648

Step:  AIC=12744.62
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level + Fasting_Blood_Sugar + Stress_Level +
    Cholesterol_LDL + Age + SBMI

                                              Df Deviance   AIC
+ Sleep_Hours                                  6    12676 12728
+ Cholesterol_LDL:Physical_Activity_Level      3    12693 12739
+ Cholesterol_HDL                              1    12699 12741
+ Cholesterol_LDL:Fasting_Blood_Sugar          1    12700 12742
+ SBMI:Fasting_Blood_Sugar                     1    12701 12743
+ Systolic_BP:Smoking_Status                   1    12702 12744
+ Age:Smoking_Status                           1    12702 12744
+ Age:Fasting_Blood_Sugar                      1    12702 12744
<none>                                              12705 12745
+ Cholesterol_LDL:Family_History               1    12703 12745
+ Age:SBMI                                     1    12703 12745
+ Fasting_Blood_Sugar:Physical_Activity_Level  3    12699 12745
+ Age:Systolic_BP                              1    12703 12745
+ Alcohol_Consumption                          2    12702 12746
+ Age:Family_History                           1    12704 12746
+ Cholesterol_LDL:Smoking_Status               1    12704 12746
+ Height_cm                                    1    12704 12746
+ SWeight                                      1    12704 12746
+ Cholesterol_Total                            1    12704 12746
+ SBMI:Systolic_BP                             1    12704 12746
+ Gender                                       1    12704 12746
+ SBMI:Family_History                          1    12704 12746
+ Diastolic_BP                                 1    12704 12746
+ SBMI:Cholesterol_LDL                         1    12704 12746
+ Fasting_Blood_Sugar:Smoking_Status           1    12705 12747
+ Age:Cholesterol_LDL                          1    12705 12747
+ Systolic_BP:Fasting_Blood_Sugar              1    12705 12747
+ Systolic_BP:Cholesterol_LDL                  1    12705 12747
+ SBMI:Smoking_Status                          1    12705 12747
+ Smoking_Status:Family_History                1    12705 12747
+ Systolic_BP:Family_History                   1    12705 12747
+ Fasting_Blood_Sugar:Family_History           1    12705 12747
+ Physical_Activity_Level:Family_History       3    12701 12747
+ Age:Physical_Activity_Level                  3    12703 12749
+ Smoking_Status:Physical_Activity_Level       3    12704 12750
+ Systolic_BP:Physical_Activity_Level          3    12704 12750
+ SBMI:Physical_Activity_Level                 3    12704 12750
+ Smoking_Status:Stress_Level                  9    12697 12755
+ Cholesterol_LDL:Stress_Level                 9    12698 12756
+ Family_History:Stress_Level                  9    12698 12756
+ Systolic_BP:Stress_Level                     9    12698 12756
+ Fasting_Blood_Sugar:Stress_Level             9    12699 12757
+ SBMI:Stress_Level                            9    12700 12758
+ Age:Stress_Level                             9    12702 12760
+ Physical_Activity_Level:Stress_Level        27    12678 12772
- Cholesterol_LDL                              1    12762 12800
- SBMI                                         1    12767 12805
- Age                                          1    12781 12819
- Systolic_BP                                  1    12881 12919
- Stress_Level                                 9    12901 12923
- Fasting_Blood_Sugar                          1    12908 12946
- Physical_Activity_Level                      3    13135 13169
- Family_History                               1    13306 13344
- Smoking_Status                               1    14554 14592

Step:  AIC=12728.24
Heart_Disease_Risk ~ Smoking_Status + Family_History + Systolic_BP +
    Physical_Activity_Level + Fasting_Blood_Sugar + Stress_Level +
    Cholesterol_LDL + Age + SBMI + Sleep_Hours

                                              Df Deviance   AIC
+ SBMI:Sleep_Hours                             6    12658 12722
+ Cholesterol_LDL:Physical_Activity_Level      3    12665 12723

In [15]:
anova(reglog.inter.step, test = "Chisq")

                                        Df Deviance    Resid. Df Resid. Dev
NULL                                    NA          NA 11999     16438.38
Smoking_Status                           1 1542.083940 11998     14896.30
Family_History                           1  532.760681 11997     14363.54
Systolic_BP                              1  497.254186 11996     13866.29
Physical_Activity_Level                  3  405.425392 11993     13460.86
Fasting_Blood_Sugar                      1  299.468484 11992     13161.39
Stress_Level                             9  190.586064 11983     12970.81
Cholesterol_LDL                          1  145.850768 11982     12824.95
Age                                      1   58.182758 11981     12766.77
SBMI                                     1   62.156389 11980     12704.62
Sleep_Hours                              6   28.378165 11974     12676.24
Cholesterol_HDL                          1    5.538579 11973     12670.70
SBMI:Sleep_Hours                         6   18.686956 11967     12652.01
Physical_Activity_Level:Cholesterol_LDL  3   11.952289 11964     12640.06
Fasting_Blood_Sugar:Cholesterol_LDL      1    5.137892 11963     12634.92
Age:Sleep_Hours                          6   13.373640 11957     12621.55
Family_History:Sleep_Hours               6   12.994673 11951     12608.55
Smoking_Status:Systolic_BP               1    2.532087 11950     12606.02
Smoking_Status:Cholesterol_HDL           1    2.120955 11949     12603.90
                                        Pr(>Chi)
NULL                                               NA
Smoking_Status                           0.000000e+00
Family_History                          7.085177e-118
Systolic_BP                             3.761899e-110
Physical_Activity_Level                  1.478964e-87
Fasting_Blood_Sugar                      4.301016e-67
Stress_Level                             3.103894e-36
Cholesterol_LDL                          1.399476e-33
Age                                      2.388634e-14
SBMI                                     3.172361e-15
Sleep_Hours                              7.973907e-05
Cholesterol_HDL                          1.860168e-02
SBMI:Sleep_Hours                         4.726315e-03
Physical_Activity_Level:Cholesterol_LDL  7.548398e-03
Fasting_Blood_Sugar:Cholesterol_LDL      2.340906e-02
Age:Sleep_Hours                          3.747166e-02
Family_History:Sleep_Hours               4.312061e-02
Smoking_Status:Systolic_BP               1.115526e-01
Smoking_Status:Cholesterol_HDL           1.452959e-01

In [16]:
#Deuxième méthode
x.mat = model.matrix(Heart_Disease_Risk~(.)^2-1, data=dataTrain) # permet d'encoder les variables qualitatives

#Pour illustrer le fonctionnement de la pénalisation, l'evolution des coefficients selon la valeur de lambda
#reglog.inter.lasso = glmnet(x=x.mat,dataTrain$Heart_Disease_Risk, family="binomial", alpha=1)
#options(repr.plot.width = 12, repr.plot.height = 10)
#plot(reglog.inter.lasso, xvar = "lambda", label = TRUE)

On determine la valeur optimale du paramètre $\lambda$, associé a la pénalisation L1, par validation croisée.

In [ ]:
y_train = as.numeric(as.character(dataTrain$Heart_Disease_Risk)) #la fonction cv.glmnet ne prend pas d'objets factors
set.seed(123) #Pour que le découpage des k folds soit toujours le même
reglog.inter.lasso.cv = cv.glmnet(y=y_train, x = x.mat,family="binomial", alpha=1)
autoplot(reglog.inter.lasso.cv)

La ligne pointillée de gauche correspond à la valeur de lambda.min qui donne l'erreur de validation croisée la plus faible. La ligne de pointillé de droite correspond à la valeur de lambda.1se qui donne la plus grande valeur de lambda telle que l'erreur reste à moins d'un écart-type de l'erreur minimale. Cette valeur de lambda donne donc une plus grande pénalisation et donc un modèle plus simple, c'est elle que nous allons utiliser.

In [ ]:
# valeur estimée
paste("Valeur de lambda estimée :", round(reglog.inter.lasso.cv$lambda.1se, 3)) #round(,3) correspond au nb de décimale après la virgule
# coefficients du modèle correspondant
coef(reglog.inter.lasso.cv, s = "lambda.1se")

Nous allons comparer les variables retenues par chaque modèle:

In [ ]:
# Variables du modèle par stepAIC
vars_step = names(coef(reglog.inter.step))[-1] # [-1] pour enlever l'intercept

# Variables du modèle lasso (en retenant lamda1se)
# On récupère la matrice des coefficients
coefs_lasso = coef(reglog.inter.lasso.cv, s = "lambda.1se")
# On garde les noms dont la valeur est différente de 0
vars_lasso = rownames(coefs_lasso)[which(coefs_lasso != 0)][-1] # [-1] pour l'intercept

#Variables communes aux deux modèles
communes = intersect(vars_step, vars_lasso)

# Variables le StepAIC a-t-il gardées que le LASSO a supprimées 
step = setdiff(vars_step, vars_lasso)

# Variables le LASSO a-t-il gardées que le StepAIC a supprimées 
lasso = setdiff(vars_lasso, vars_step)

paste("Nombre de variables communes:",length(communes))
paste("Nombre de variables uniquement dans le modèle stepAIC:",length(step))
paste("Nombre de variables uniquement dans le modèle LASSO:",length(lasso))

Les deux modèles obtenus sont complètements différents (seulement deux variables communes). Cela peut s'expliquer par le fait que reglog.inter.step considère les variables qualitatives comme des "blocs"alors que reglog.inter.lasso.cv considère chaque modalité.

In [ ]:
#Comparaisons matrices de confusions
table(reglog.inter.step$fitted.values > 0.5, dataTrain[, "Heart_Disease_Risk"])
proba_lasso = predict(reglog.inter.lasso.cv, newx = x.mat, type = "response")  
table(proba_lasso > 0.5,dataTrain$Heart_Disease_Risk)

### Prévision de l'échantillon test

**Matrices de confusions**

In [ ]:
#Prévision modèle sans interaction sans selection de variable
pred.log <- predict(reglog, newdata = dataTest, type = "response")
#Prévision modèle sans interaction avec selection de variable
pred.log.step <- predict(reglog.stepAIC, newdata = dataTest, type = "response")
#Prévision modèle avec interaction par stepAIC
pred.log.inter.step <- predict(reglog.inter.step, newdata = dataTest, type = "response")
#Prévision modèle avec interaction par lasso
x.mat.test = model.matrix(Heart_Disease_Risk~(.)^2-1, data=dataTest)
pred.log.inter.lasso <- predict(reglog.inter.lasso.cv, newx = x.mat.test, type = "response")

# Matrices de confusion
print("Matrice de confusion du modèle reglog :")
table(pred.log > 0.5, dataTest[, "Heart_Disease_Risk"])
print("Matrice de confusion du modèle reglog.stepAIC :")
table(pred.log.step > 0.5, dataTest[, "Heart_Disease_Risk"])
print("Matrice de confusion du modèle reglog.inter.step :")
table(pred.log.inter.step > 0.5, dataTest[, "Heart_Disease_Risk"])
print("Matrice de confusion du modèle reglog.inter.lasso.cv :")
table(pred.log.inter.lasso> 0.5, dataTest[, "Heart_Disease_Risk"])

**Courbe ROC**

In [ ]:
options(repr.plot.width = 6, repr.plot.height = 6)
par(mfrow = c(1, 1))

# modèle sans interaction sans selection de variable
predlogit <- prediction(pred.log, dataTest[, "Heart_Disease_Risk"])
perflogit <- performance(predlogit, "tpr", "fpr")

#Prévision modèle sans interaction avec selection de variable
predlogit.step <- prediction(pred.log.step, dataTest[, "Heart_Disease_Risk"])
perflogit.step <- performance(predlogit.step, "tpr", "fpr")

#Prévision modèle avec interaction par stepAIC
predlogit.interstep <- prediction(pred.log.inter.step, dataTest[, "Heart_Disease_Risk"])
perflogit.inter.step <- performance(predlogit.interstep, "tpr", "fpr")

#Prévision modèle avec interaction par lasso
predlogit.inter.lasso <- prediction(pred.log.inter.lasso, dataTest[, "Heart_Disease_Risk"])
perflogit.inter.lasso <- performance(predlogit.inter.lasso, "tpr", "fpr")

plot(perflogit, col = "blue",lty=2, main = "Courbe ROC ")
plot(perflogit.step,col="orange",lty=2,add=TRUE)
plot(perflogit.inter.step,col="green",lty=1,add=TRUE) 
plot(perflogit.inter.lasso,col="red",lty=1,add=TRUE) 

legend("right", legend=c("reglog", "reglog.stepAIC", "reglog.inter.step","reglog.inter.lasso.cv"),
       col=c("blue","orange","green","red"), lty=c(2,2,1,1), text.font=1,    cex=0.8)

## Modèle SVM

In [11]:
library(e1071)

Attachement du package : 'e1071'


L'objet suivant est masqué depuis 'package:ggplot2':

    element

Justifier le type de noyau utilisé. On part du principe que les données ne sont pas linéairement séparables (très peu probable).

In [12]:
# optimisation
# cost est paramètre qui permet d'ajuster la tolérance aux points mal classées. Plus il est grand, plus il y en a. 
# gamma permet de régler l'influence d'un point. Plus il est élevé, plus l'influence d'un point est courte.
# kernel par défaut (radial)
svm.tune = tune.svm(Heart_Disease_Risk ~ ., data = dataTrain, cost = c(1,1.25,1.5,1.75,2), 
    gamma = seq(0.02, 0.1, by = 0.02))
plot(svm.dis.tune)

ERROR: Error: objet 'dataTrain' introuvable

In [ ]:
# apprentissage
svm.tune$best.parameters
svm.best=svm(Heart_Disease_Risk~.,data=dataTrain,cost = svm.tune$best.parameters$cost, 
    gamma = svm.tune$best.parameters$gamma)